---
title: "Additional sims - Formatted tables output"
format:
  pdf:
    keep-tex: true
echo: false
warning: false
---


```{r packages}
library(knitr)
library(kableExtra)
library(tidyverse)
```

```{r load}
p <- 100
N <- 5000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, ".RData")
load(file)
```

```{r multi}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
  "FOCuS0_alt" = "FOCuS0",
  "MdFOCuS0_2d_part" = "MdFOCuS0 2d MR",
  "MdFOCuS0_1d_part" = "MdFOCuS0 1d MR",
  "MdFOCuS_part" = "MdFOCuS 2d MR",
  "MdFOCuS_1d_part" = "MdFOCuS 1d MR")
   )

tot_summ <- tot_res %>% mutate(dd = est - 500, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

## Pre-change mean known

```{r}
# known change
out <- wide_summary |> 
  select(magnitude, density, FOCuS0, `MdFOCuS0 1d MR`, `MdFOCuS0 2d MR`, `ocd (ora)`)
  
out %>% 
  kable(caption = "Average detection delay in the pre-change mean known scenario with 100-dimensional time series for a change at time $t = 500$.
Best results per row are highlighted in bold.",
        label = "tab:dd-known",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")

```

```{r}
# known change
out <- wide_sd  |> 
  select(magnitude, FOCuS0, `MdFOCuS0 1d MR`, `MdFOCuS0 2d MR`, `ocd (ora)`)
out %>% 
    kable(caption = "Standard deviation of the detection delay in the pre-change mean known scenario with 100-dimensional time series for a change at time $t = 500$. Best results per row are highlighted in bold.",
        label = "tab:variance-known",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")
```


```{r}
# known change
out <- wide_summary |> 
  select(magnitude, density, FOCuS, `MdFOCuS 1d MR`, `MdFOCuS 2d MR`, `ocd (est)`)
  
out %>% 
  kable(caption = "Average detection delay in the pre-change mean unknown scenario with 100-dimensional time series for a change at time $t = 500$.
Best results per row are highlighted in bold.",
        label = "tab:dd-known",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")

```

```{r}
# known change
out <- wide_sd  |> 
  select(magnitude, FOCuS, `MdFOCuS 1d MR`, `MdFOCuS 2d MR`, `ocd (est)`)
out %>% 
    kable(caption = "Standard deviation of the detection delay in the pre-change mean unknown scenario with 100-dimensional time series for a change at time $t = 500$. Best results per row are highlighted in bold.",
        label = "tab:variance-known",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")
```



```{r}
p <- 3
N <- 10000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "_alt.RData")
load(file)
```


```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
   "FOCuS0_alt" = "FOCuS0",
   "MdFOCuS_part" = "MdFOCuS MR",
   "MdFOCuS0_part" = "MdFOCuS0 MR")
   )

tot_summ <- tot_res %>% mutate(dd = est - 500, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# known change
out <- wide_summary %>%
  select(magnitude, density, FOCuS0, "MdFOCuS0 MR", "md-FOCuS0", "ocd (ora)") %>%
  filter(magnitude < 2)
  
out %>% 
  kable(caption = "Average detection delay in the pre-change mean known scenario with 3-dimensional time series for a change at time $t = 500$.
Best results per row are highlighted in bold.  Results controlling the false positive rate.",
        label = "tab:dd-known",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")

```

```{r}
# known change
out <- wide_sd %>%
  select(magnitude, FOCuS0, "MdFOCuS0 MR", "md-FOCuS0", "ocd (ora)") %>% 
  filter(magnitude < 2)
  
out %>% 
    kable(caption = "Average detection delay in the pre-change mean known scenario with 3-dimensional time series for a change at time $t = 500$. Best results per row are highlighted in bold. Results controlling the false positive rate. ",
        label = "tab:variance-known",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")
```


```{r}
# unknown change
out <- wide_summary %>%
    select(magnitude, density, FOCuS, "FOCuS0 (est)", "MdFOCuS MR", "md-FOCuS", "ocd (est)") %>% 
    filter(magnitude > 0.25)
out %>% 
  kable(caption = "Average detection delay in the pre-change mean unknown scenario with 3-dimensional time series for a change at time $t = 500$.
Best results per row are highlighted in bold.  Results controlling the false positive rate.",
        label = "tab:dd-unknown",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")

```



```{r}
# unknown change
out <- wide_sd %>%
    select(magnitude, FOCuS, "FOCuS0 (est)", "MdFOCuS MR", "md-FOCuS", "ocd (est)") %>% 
    filter(magnitude > 0.25)

out %>% 
      kable(caption = "Standard deviation of the detection delay in the pre-change mean unknown scenario with 3-dimensional time series for a change at time $t = 500$.
Best results per row are highlighted in bold.  Results controlling the false positive rate.",
        label = "tab:variance-unknown",
        format = "latex", booktabs = TRUE, linesep = c('', '',  '\\addlinespace')) %>%
  kable_styling(latex_options = "hold_position")

```
