---
title: "Formatted tables output"
format:
  pdf:
    keep-tex: true
echo: false
warning: false
---

```{r}
library(knitr)
library(kableExtra)
library(tidyverse)
```

# Average run length Tuning

## 3-dimentional sequences

```{r}
p <- 3
N <- 5000
cp <- 1000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "cp", cp, ".RData")
load(file)
```

```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
   "MdFOCuS0 MR" = "MdFOCuS Sp",
   "MdFOCuS MR" = "MdFOCuS0 Sp")
   )

tot_summ <- tot_res %>% filter(magnitude !=  0.625) %>% mutate(dd = est - cp, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# Assuming wide_summary is your tibble
reordered_summary <- wide_summary %>%
  select(
    magnitude, 
    density, 
    FOCuS0, 
    `MdFOCuS0 Sp`, 
    `ocd (ora)`, 
    `FOCuS0 (est 250)`, 
    FOCuS, 
    `MdFOCuS Sp`, 
    `ocd (est 250)`
  )

# Add the header row to visually separate the columns
reordered_summary %>%
  kable(
    caption = paste0("Average detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:dd",
    format = "latex", 
    booktabs = TRUE, 
    linesep = c(rep('', p-1),  '\\addlinespace')
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 2, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

```{r}
combined_sd <- wide_sd %>%
  select(magnitude, FOCuS0, `MdFOCuS0 Sp`, `ocd (ora)`, `FOCuS0 (est 250)`, FOCuS, `MdFOCuS Sp`, `ocd (est 250)`)

# Create the table with headers
combined_sd %>%
  kable(
    caption = paste0("Standard deviation of the detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:variance-known",
    format = "latex",
    linesep = c(''),
    booktabs = TRUE
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 1, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

## 100-dimentional sequences

```{r}
p <- 100
N <- 5000
cp <- 1000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "cp", cp, ".RData")
load(file)
```

```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
  "FOCuS0_alt" = "FOCuS0",
  "MdFOCuS0_2d_part" = "MdFOCuS0 2d Sp",
  "MdFOCuS0_1d_part" = "MdFOCuS0 1d Sp",
  "MdFOCuS_2d_part" = "MdFOCuS 2d Sp",
  "MdFOCuS_1d_part" = "MdFOCuS 1d Sp")
   )

tot_summ <- tot_res %>% filter(magnitude !=  0.625) %>% mutate(dd = est - cp, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# Assuming wide_summary is your tibble
reordered_summary <- wide_summary %>%
  select(
    magnitude, 
    density, 
    FOCuS0, 
    `MdFOCuS0 2d Sp`,
    `ocd (ora)`, 
    `FOCuS0 (est 250)`, 
    FOCuS, 
    `MdFOCuS 2d Sp`, 
    `ocd (est 250)`
  )

# Add the header row to visually separate the columns
reordered_summary %>%
  kable(
    caption = paste0("Average detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:dd",
    format = "latex", 
    booktabs = TRUE, 
    linesep = c(rep('', n_distinct(reordered_summary$density)-1),  '\\addlinespace')
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 2, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

```{r}
combined_sd <- wide_sd %>%
  select(
    magnitude,
    FOCuS0,
    `MdFOCuS0 2d Sp`,
    `ocd (ora)`,
    `FOCuS0 (est 250)`,
    FOCuS,
    `MdFOCuS 2d Sp`,
    `ocd (est 250)`
  )

# Create the table with headers
combined_sd %>%
  kable(
    caption = paste0("Standard deviation of the detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:variance-known",
    format = "latex",
    linesep = c(''),
    booktabs = TRUE
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 1, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

# 5-dim sequences

## 5-dimentional sequences

```{r}
p <- 5
N <- 5000
cp <- 1000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "cp", cp, ".RData")
load(file)
```

```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
                       "MdFOCuS MR" = "MdFOCuS Sp",
                       "MdFOCuS0 MR" = "MdFOCuS0 Sp")
  )

tot_summ <- tot_res %>% filter(magnitude !=  0.625) %>% mutate(dd = est - cp, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
  )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
  ) %>%
  pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# Assuming wide_summary is your tibble
reordered_summary <- wide_summary %>%
  select(
    magnitude, 
    density, 
    FOCuS0, 
    `MdFOCuS0 Sp`, 
    `ocd (ora)`, 
    `FOCuS0 (est 250)`,
    FOCuS, 
    `MdFOCuS Sp`, 
    `ocd (est 250)`
    )

# Add the header row to visually separate the columns
reordered_summary %>%
  kable(
    caption = paste0("Average detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:dd",
    format = "latex", 
    booktabs = TRUE, 
    linesep = c(rep('', p-1),  '\\addlinespace')
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 2, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

```{r}
combined_sd <- wide_sd %>%
  select(magnitude,     FOCuS0, 
    `MdFOCuS0 Sp`, 
    `ocd (ora)`, 
    `FOCuS0 (est 250)`,
    FOCuS, 
    `MdFOCuS Sp`, 
    `ocd (est 250)`
    )

# Create the table with headers
combined_sd %>%
  kable(
    caption = paste0("Standard deviation of the detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:variance-known",
    format = "latex",
    linesep = c(''),
    booktabs = TRUE
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 1, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

# False positive rate

## 50 dimentional sequences

```{r}
p <- 50
N <- 20000
cp <- 10000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "cp", cp, "_alt.RData")
load(file)
```


```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
  "FOCuS0_alt" = "FOCuS0",
  "MdFOCuS0_2d_part" = "MdFOCuS0 2d Sp",
  "MdFOCuS0_1d_part" = "MdFOCuS0 1d Sp",
  "MdFOCuS_2d_part" = "MdFOCuS 2d Sp",
  "MdFOCuS_1d_part" = "MdFOCuS 1d Sp")
   )

tot_summ <- tot_res %>% filter(magnitude !=  0.625) %>% mutate(dd = est - cp, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# Assuming wide_summary is your tibble
reordered_summary <- wide_summary %>%
  select(
    magnitude, 
    density, 
    FOCuS0, 
    `MdFOCuS0 1d Sp`,
    `MdFOCuS0 2d Sp`,
    `FOCuS0 (est)`, 
    FOCuS, 
    `MdFOCuS 1d Sp`,
    `MdFOCuS 2d Sp`
  )

# Add the header row to visually separate the columns
reordered_summary %>%
  kable(
    caption = paste0("Average detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold. Results are by controlling the false positive rate."),
    label = "tab:dd",
    format = "latex", 
    booktabs = TRUE, 
    linesep = c(rep('', n_distinct(reordered_summary$density)-1),  '\\addlinespace')
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 2, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```

```{r}
combined_sd <- wide_sd %>%
  select(
    magnitude,
    FOCuS0, 
    `MdFOCuS0 1d Sp`,
    `MdFOCuS0 2d Sp`,
    `FOCuS0 (est)`, 
    FOCuS, 
    `MdFOCuS 1d Sp`,
    `MdFOCuS 2d Sp`
  )

# Create the table with headers
combined_sd %>%
  kable(
    caption = paste0("Standard deviation of the detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold. Results are by controlling the false positive rate."),
    label = "tab:variance-known",
    format = "latex",
    linesep = c(''),
    booktabs = TRUE
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  ) %>%
  add_header_above(c(" " = 1, "Pre-change Known" = 3, "Pre-change Unknown" = 4))
```


# Effect of the estimation in pre-change mean unknown case

```{r}
p <- 3
N <- 5000
cp <- 1000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "cp", cp, ".RData")
load(file)
```

```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
   "MdFOCuS0 MR" = "MdFOCuS Sp",
   "MdFOCuS MR" = "MdFOCuS0 Sp")
   )

tot_summ <- tot_res %>% filter(magnitude !=  0.625) %>% mutate(dd = est - cp, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# Assuming wide_summary is your tibble
reordered_summary <- wide_summary %>%
  select(
    magnitude,
    density,
    FOCuS0,
    `FOCuS0 (est 500)`,
    `FOCuS0 (est 250)`,
    `FOCuS0 (est 100)`,
    `ocd (ora)`,
    `ocd (est 500)`,
    `ocd (est 250)`,
    `ocd (est 100)`
  )

# Add the header row to visually separate the columns
reordered_summary %>%
  kable(
    caption = paste0("Average detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:dd",
    format = "latex", 
    booktabs = TRUE, 
    linesep = c(rep('', p-1),  '\\addlinespace')
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  )
```

```{r include = F}
combined_sd <- wide_sd %>%
  select(magnitude,
             FOCuS0,
    `FOCuS0 (est 500)`,
    `FOCuS0 (est 250)`,
    `FOCuS0 (est 100)`,
    `ocd (ora)`,
    `ocd (est 500)`,
    `ocd (est 250)`,
    `ocd (est 100)`
         )

# Create the table with headers
combined_sd %>%
  kable(
    caption = paste0("Standard deviation of the detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:variance-known",
    format = "latex",
    linesep = c(''),
    booktabs = TRUE
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  )
```

For sequence of 100d
```{r}
p <- 100
N <- 5000
cp <- 1000
# loading thresholds from past simulations
file <- paste0("results/det_del_", "p", p, "N", N, "cp", cp, ".RData")
load(file)
```

```{r}
tot_res <- Reduce(rbind, runs_res) %>%
  mutate(algo = recode(algo,
   "MdFOCuS0 MR" = "MdFOCuS0 Sp",
   "MdFOCuS MR" = "MdFOCuS Sp",
   "FOCuS0_alt" = "FOCuS0")
   )

tot_summ <- tot_res %>% filter(magnitude !=  0.625) %>% mutate(dd = est - cp, density = density * p) %>% 
  group_by(magnitude, density, algo) %>%
  summarise(
    avg_dd = round(mean(if_else(dd < 0, NA, dd), na.rm = T), 2),
    sd_dd = round(sd(if_else(dd < 0, NA, dd), na.rm = T), 2),
    fpr = mean(dd<0)
    )

```

```{r}
wide_summary <- tot_summ %>% 
  pivot_wider(names_from = algo, values_from = avg_dd, id_cols = -c(fpr, sd_dd))

wide_sd <- tot_summ %>%
  group_by(magnitude, algo) %>%
  summarise(
    sd_dd = round(sd(avg_dd), 2),
    ) %>%
    pivot_wider(names_from=algo, values_from = sd_dd)

```

```{r}
# Assuming wide_summary is your tibble
reordered_summary <- wide_summary %>%
  select(
    magnitude,
    density,
    FOCuS0,
    `FOCuS0 (est 500)`,
    `FOCuS0 (est 250)`,
    `FOCuS0 (est 100)`,
    `ocd (ora)`,
    `ocd (est 500)`,
    `ocd (est 250)`,
    `ocd (est 100)`
  )

# Add the header row to visually separate the columns
reordered_summary %>%
  kable(
    caption = paste0("Average detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:dd",
    format = "latex", 
    booktabs = TRUE, 
    linesep = c(rep('', p-1),  '\\addlinespace')
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  )
```

```{r include = F}
combined_sd <- wide_sd %>%
  select(magnitude,
             FOCuS0,
    `FOCuS0 (est 500)`,
    `FOCuS0 (est 250)`,
    `FOCuS0 (est 100)`,
    `ocd (ora)`,
    `ocd (est 500)`,
    `ocd (est 250)`,
    `ocd (est 100)`
         )

# Create the table with headers
combined_sd %>%
  kable(
    caption = paste0("Standard deviation of the detection delay with ", p, "-dimensional time series for a change at time $t = ", cp, "$. Pre-change parameter known on the left, unknown on the right. Best results per row are highlighted in bold."),
    label = "tab:variance-known",
    format = "latex",
    linesep = c(''),
    booktabs = TRUE
  ) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down"), 
    font_size = 12  # Adjust font size as needed
  )
```